title: "Jordy Devalor Nguizo Mothilo"
logo: blob:https://web.whatsapp.com/264e2002-bc99-49c3-aac0-3ea77f682040
description: Portfolio Datascientist & ML Engineer
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
